FROM nciccbr/ccbr_ubuntu_22.04:v4

WORKDIR /opt2
# Install BBtools
RUN wget https://sourceforge.net/projects/bbmap/files/BBMap_38.87.tar.gz && \
    tar -xzf BBMap_38.87.tar.gz && \
    rm BBMap_38.87.tar.gz

# Add BBtools to PATH
ENV PATH="/opt2/bbmap":$PATH

# Copy Dockerfile and other files in a single layer
COPY ${DOCKERFILE} /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod -R a+rx /opt2 && chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}