name: ccbr_r_phylo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.5.2
  - r-ape
  - r-phangorn
  - r-ggplot2
  - r-circlize
  - r-viridislite
  - r-seqinr
  - r-optparse
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-tibble
  - r-readr
  - r-stringr
  - r-purrr
  - r-jsonlite
  - r-yaml
  - r-glue
  - r-cli
  - r-pheatmap
  - r-rcolorbrewer
  - r-patchwork
  - bioconductor-ggtree
  - bioconductor-treeio
  - bioconductor-complexheatmap
  - bioconductor-rtracklayer
  - bioconductor-biostrings
  - bioconductor-rsamtools
  - bioconductor-genomicalignments
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-xvector
  - bioconductor-decipher
  - bioconductor-msa
  - bioconductor-shortread
  - samtools
  - bcftools
  - htslib
  - bedtools
  - seqkit
  - mafft
  - wget
  - curl
  - ca-certificates
