FROM nciccbr/ccbr_ubuntu_22.04:v4

# Build time variables
ARG DOCKERFILE="Dockerfile"
ENV DOCKERFILE=${DOCKERFILE}
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}
ARG IMAGENAME="000000"
ENV IMAGENAME=${IMAGENAME}
ARG BASEIMAGENAME="000000"
ENV BASEIMAGENAME=${BASEIMAGENAME}

# COPY fastqc_v0.11.9.zip /opt2
ADD https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip /opt2/

# unzip and set permissions
WORKDIR /opt2
RUN unzip fastqc_v0.11.9.zip && rm -f fastqc_v0.11.9.zip && chmod 755 /opt2/FastQC/fastqc

# Add fastqc to PATH
ENV PATH="/opt2/FastQC":$PATH

# Copy Dockerfile and other files in a single layer
COPY ${DOCKERFILE} /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod -R a+rx /opt2 && chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
