FROM nciccbr/ccbr_atacseq:v11-feat

LABEL maintainer="Vishal Koparde *(kopardev on GitHub)*"
LABEL github_handle="kopardev"

# Build time variables
ARG DOCKERFILE="Dockerfile"
ENV DOCKERFILE=${DOCKERFILE}
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}
ARG IMAGENAME="000000"
ENV IMAGENAME=${IMAGENAME}
ARG BASEIMAGENAME="000000"
ENV BASEIMAGENAME=${BASEIMAGENAME}

# Install BiocT2T and TxDb.Hsapiens.NCBI.CHM13v2 for hs1/hs1_chrR T2T genome support
RUN Rscript -e 'if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager"); BiocManager::install("BiocT2T", ask=FALSE)' && \
    Rscript -e 'BiocT2T::install_early_t2t_txdb()'

# Copy Dockerfile and other files in a single layer
COPY ${DOCKERFILE} /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod -R a+rx /opt2 && chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}

WORKDIR /data2
