FROM nciccbr/ccbr_ubuntu_22.04:v4

# Build time variables
ARG DOCKERFILE="Dockerfile"
ENV DOCKERFILE=${DOCKERFILE}
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}
ARG IMAGENAME="000000"
ENV IMAGENAME=${IMAGENAME}
ARG BASEIMAGENAME="000000"
ENV BASEIMAGENAME=${BASEIMAGENAME}

# R is required for ebseq
RUN apt-get update && apt-get upgrade -y && \
    apt-get install --yes --no-install-recommends r-base

# Download and install RSEM 1.3.1
WORKDIR /opt2
RUN wget https://github.com/deweylab/RSEM/archive/v1.3.1.tar.gz -O rsem-1.3.1.tar.gz && \
    tar -xzvf rsem-1.3.1.tar.gz && \
    cd RSEM-1.3.1 && \
    make && \
    make ebseq && \
    make install && \
    cd .. && \
    rm -rf RSEM-1.3.1 rsem-1.3.1.tar.gz

# Copy Dockerfile and other files in a single layer
COPY ${DOCKERFILE} /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod -R a+rx /opt2 && chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}