FROM nciccbr/ccbr_ubuntu_22.04:v4

LABEL maintainer="Vishal Koparde *(kopardev on GitHub)*"
LABEL github_handle="kopardev"

# Build time variables
ARG DOCKERFILE="Dockerfile"
ENV DOCKERFILE=${DOCKERFILE}
ARG BUILD_DATE="000000"
ENV BUILD_DATE=${BUILD_DATE}
ARG BUILD_TAG="000000"
ENV BUILD_TAG=${BUILD_TAG}
ARG REPONAME="000000"
ENV REPONAME=${REPONAME}
ARG IMAGENAME="000000"
ENV IMAGENAME=${IMAGENAME}
ARG BASEIMAGENAME="000000"
ENV BASEIMAGENAME=${BASEIMAGENAME}

WORKDIR /opt2
RUN wget 'https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.2.1/bwa-mem2-2.2.1_x64-linux.tar.bz2' && \
    tar -xjvf bwa-mem2-2.2.1_x64-linux.tar.bz2 && rm -f bwa-mem2-2.2.1_x64-linux.tar.bz2
WORKDIR /opt2/bwa-mem2.x86_64-linux
RUN chmod a+x bwa-mem2 
ENV PATH="/opt2/bwa-mem2.x86_64-linux/:$PATH"

# Copy Dockerfile and other files in a single layer
COPY ${DOCKERFILE} /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}
RUN chmod -R a+rx /opt2 && chmod a+r /opt2/Dockerfile_${REPONAME}.${BUILD_TAG}

# Set PATH and working directory
WORKDIR /data2
