name: build-docker-manual

run-name: ${{ inputs.dockerfile }}

on:
  # push:
  #   branches:
  #     - smaller_base_image
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      dockerfile:
        type: string
        description: path to the Dockerfile in the repo (e.g. common/ccbr_bwa/Dockerfile)
        required: true
      push:
        type: boolean
        description: Push to DockerHub (leave unchecked to just build the container without pushing)
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        if: ${{ github.event.inputs.push == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare build-time variables and set variables
        id: vars
        run: |
          bash scripts/prepare_for_build ${{ github.event.inputs.dockerfile }} 
      - name: check variables
        id: check
        run: |
            echo $DOCKERFILE
            echo $IMAGENAME
            echo $BASEIMAGENAME
            echo $BUILD_DATE
            echo $BUILD_TAG
            echo $REPONAME
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ env.DOCKERFILE }}
          push: false
          tags: ${{ env.IMAGENAME }}
          build-args: |
            DOCKERFILE=${{ env.DOCKERFILE }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_TAG=${{ env.BUILD_TAG }}
            REPONAME=${{ env.REPONAME }}
            IMAGENAME=${{ env.IMAGENAME }}
            BASEIMAGENAME=${{ env.BASEIMAGENAME }}
      - name: List Docker images
        run: docker images
      # - name: Update Docker Hub Description
      #   if: ${{ github.event.inputs.push == 'true' }}
      #   uses: peter-evans/dockerhub-description@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ steps.metadata.outputs['dockerhub_namespace'] }}/${{ steps.metadata.outputs['image_name'] }}
      #     readme-filepath: tmp_README.md
# docker buildx build \
#     --progress=plain \
#     --build-arg BUILD_DATE=${dt} \
#     --build-arg BUILD_TAG=${tag} \
#     --build-arg REPONAME=${reponame} \
#     --build-arg IMAGENAME=${imagename} \
#     --build-arg BASENAME=${basename} \
#     -t ${imagename} \
#     -f ${dockerfile} .