name: build-docker-manual

run-name: ${{ inputs.dockerfile }}

on:
  # push:
  #   branches:
  #     - smaller_base_image
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      dockerfile:
        type: string
        description: path to the Dockerfile in the repo (e.g. common/ccbr_bwa/Dockerfile)
        required: true
      push:
        type: boolean
        description: Push to DockerHub (leave unchecked to just build the container without pushing)
        required: true
        default: false

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        if: ${{ github.event.inputs.push == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_VK }}
          password: ${{ secrets.DOCKERHUBRW_TOKEN_VK }}
      - name: Get branch name
        id: get_branch
        run: |
          # Determine the branch name
          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          elif [[ "${GITHUB_REF}" == "refs/pull/"* ]]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF}"
          fi
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
      - name: Prepare build-time variables and set variables
        id: vars
        run: |
          bash scripts/prepare_for_build ${{ github.event.inputs.dockerfile }} ${{ env.BRANCH_NAME }}
      - name: check variables and create readme
        id: check_and_create_readme
        run: |
            echo $DOCKERFILE
            echo $IMAGENAME
            echo $BASEIMAGENAME
            echo $BUILD_DATE
            echo $BUILD_TAG
            echo $REPONAME
            echo " # ${{ github.repository }} $IMAGENAME" > tmp_README.md
            echo "Dockerfile source: https://github.com/${{ github.repository }}/blob/${{ github.sha }}/${{ github.event.inputs.dockerfile }}" >> tmp_README.md
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          file: ${{ env.DOCKERFILE }}
          push: ${{ github.event.inputs.push }}
          tags: ${{ env.IMAGENAME }}
          build-args: |
            DOCKERFILE=${{ env.DOCKERFILE }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_TAG=${{ env.BUILD_TAG }}
            REPONAME=${{ env.REPONAME }}
            IMAGENAME=${{ env.IMAGENAME }}
            BASEIMAGENAME=${{ env.BASEIMAGENAME }}
      - name: List Docker images
        run: docker images
      - name: Update Docker Hub Description
        if: ${{ (github.event.inputs.push == 'true') && (steps.build-and-push.outcome == 'success') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_VK }}
          password: ${{ secrets.DOCKERHUBRW_TOKEN_VK }}
          repository: nciccbr/${{ env.IMAGENAME }}
          readme-filepath: tmp_README.md