# This GitHub Actions workflow is designed to trigger a manual Docker build for each modified Dockerfile.
# 
# Workflow Name: detect-and-trigger
# Short Description: Trigger Build Docker Manual for Each modified Dockerfile
#
# Triggers:
# - On push events to any branch except 'main' and 'dev', if any Dockerfile.* is modified.
# - On pull request events to 'main' and 'dev' branches, if any Dockerfile.* is modified.
#
# Jobs:
# - detect-and-trigger:
#   - Runs on the latest Ubuntu environment.
#   - Steps:
#     1. Check out the repository using actions/checkout@v4.
#     2. Identify modified Dockerfiles using git diff and store them in the environment variable 'dockerfiles'.
#     3. For each modified Dockerfile, trigger the 'build-docker-manual' workflow with the Dockerfile path and additional parameters.
#
# Environment Variables:
# - GITHUB_TOKEN: Used for authentication to trigger the 'build-docker-manual' workflow.
name: detect-and-trigger

on:
  push:
    branches:
      - '**autobuild**'  # Only trigger if the branch name contains "autobuild"
    paths:
      - '**/Dockerfile.*'  # Only trigger if a Dockerfile.* is modified in any directory

  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**/Dockerfile.*'  # Only trigger if a Dockerfile.* is modified in any directory

jobs:
  detect-and-trigger:
    runs-on: ubuntu-latest

    # Define environment variables
    env:
      SUFFIX: ${{ github.base_ref == 'main' && github.event_name == 'pull_request' && 'main' || github.base_ref == 'dev' && github.event_name == 'pull_request' && 'dev' || 'feat' }}


    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - id: changed-files
        name: Check changed files
        uses: knu/changed-files@v1
        with:
          paths: |
            **/Dockerfile.*

      - name: Show changed files
        id: print-changed-files
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.changed_files }}" | sed 's/^/  /'
          echo "Matched files:"
          echo "${{ steps.changed-files.outputs.matched_files }}" | sed 's/^/  /'

      - name: Trigger build-docker-manual for each modified Dockerfile
        id: trigger-build-docker-manual
        if: steps.changed-files.outputs.matched_files
        run: |
          MODIFIED_DOCKERFILES=$(echo "${{ steps.changed-files.outputs.matched_files }}" | tr '\n' ' ')
          REF=${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}
          STATUS=0

          for DOCKERFILE in $MODIFIED_DOCKERFILES; do
            echo "Triggering build-docker-manual for $DOCKERFILE"

            # Trigger the build-docker-manual workflow with the Dockerfile as an input
            RESPONSE=$(gh workflow run build-docker-manual.yml \
              --ref $REF \
              --field dockerfile=$DOCKERFILE \
              --field dockerhub_namespace=nciccbr \
              --field suffix=${{ env.SUFFIX }} \
              --field push=true)

            # Check if the workflow was triggered successfully
            if [[ $? -ne 0 ]]; then
              echo "Failed to trigger build-docker-manual for $DOCKERFILE"
              STATUS=1
              break
            fi

            # Extract workflow run ID from response to monitor its status
            RUN_ID=$(echo "$RESPONSE" | grep -oP '(?<=workflow run ID: )\d+')

            # Poll the status of the triggered workflow until it completes
            while true; do
              RUN_STATUS=$(gh run view $RUN_ID --json conclusion -q .conclusion)
              
              if [[ "$RUN_STATUS" == "success" ]]; then
                echo "build-docker-manual completed successfully for $DOCKERFILE"
                break
              elif [[ "$RUN_STATUS" == "failure" || "$RUN_STATUS" == "cancelled" ]]; then
                echo "build-docker-manual failed for $DOCKERFILE"
                STATUS=1
                break
              else
                echo "Waiting for build-docker-manual to complete for $DOCKERFILE..."
                sleep 10
              fi
            done
          done

          # Exit with a failure if any build-docker-manual workflow failed
          if [[ $STATUS -ne 0 ]]; then
            echo "One or more build-docker-manual workflows failed."
            exit 1
          else
            echo "All build-docker-manual workflows completed successfully."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
